### ISSUE TITLE
Permaliens cassés

### ISSUE THREAD

**Issue by Ayack** [matchID-project/deces-dataprep#139]
Bonjour, depuis ce week-end tous les permaliens ont changés, cassant l'alignement avec Wikidata (plus de 45 000 personnes). Cf. cette discussion : https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Le_Bistro_du_jour#Les_identifiants_MatchID_sont_modifiés_!_(copie_brute_du_message_posté_par_mes_soins_sur_le_bistro_du_projet_Wikidata)

**Comment by rhanka** [comment]
Bonjour, nous avions mis à jour un parsing du fichier de l'INSEE suite au changement de spécification du fichier notamment pour les actes décès en N. Certaines opposition au fichier des décès n'étaient pas appliquées de ce fait (une 30aine).
Cela a induit un bug colatéral de changement des permaliens dès lors qu'il y avait un N dedans.
Je viens de mettre en place un correctif en cours de test avant déploiement
#140

**Comment by TONTONFLINGUEUR** [comment]
Bonsoir Rhanka,
merci pour cette réponse.

**Comment by rhanka** [comment]
Bug resolu, a priori, le laisse le temps du doute et surtout d'une petite confirmation de votre part !

**Comment by TONTONFLINGUEUR** [comment]
Rhanka, c'est vérifié et tout semble bon à nouveau. Un grand merci. Cordialement.

**Comment by rhanka** [comment]
Merci du retour !

**Comment by TONTONFLINGUEUR** [comment]
Je vous en prie, c'est tout naturel.
